version: '3.9'

services:
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MegaDifficultPassword
      - MYSQL_PASSWORD=TheDifficultPassword
      - MYSQL_USER=admin
      - MYSQL_DATABASE=warehouse